global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'hypernova-production'
    environment: 'production'

scrape_configs:
  - job_name: 'hypernova-backend'
    metrics_path: '/metrics'
    scheme: https
    static_configs:
      - targets: ['hypernova-backend-azgf.onrender.com']
        labels:
          service: 'backend'
          env: 'production'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
